// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF42tHhXkW2Q5ejbCbrl2MjD9Mrykuy9M',
    appId: '1:124863240778:web:5628c5032f39ee4237a4b3',
    messagingSenderId: '124863240778',
    projectId: 'emergency-c1b8b',
    authDomain: 'emergency-c1b8b.firebaseapp.com',
    storageBucket: 'emergency-c1b8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6oRhC5yiYxgiRr5D7Dwz_9MPqCXDTok',
    appId: '1:124863240778:android:b75b03fe5c229e9c37a4b3',
    messagingSenderId: '124863240778',
    projectId: 'emergency-c1b8b',
    storageBucket: 'emergency-c1b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATm015luxDJ1n18I1ZncDVfcB2GuFpdYk',
    appId: '1:124863240778:ios:78130ebb04d542a137a4b3',
    messagingSenderId: '124863240778',
    projectId: 'emergency-c1b8b',
    storageBucket: 'emergency-c1b8b.appspot.com',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATm015luxDJ1n18I1ZncDVfcB2GuFpdYk',
    appId: '1:124863240778:ios:78130ebb04d542a137a4b3',
    messagingSenderId: '124863240778',
    projectId: 'emergency-c1b8b',
    storageBucket: 'emergency-c1b8b.appspot.com',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF42tHhXkW2Q5ejbCbrl2MjD9Mrykuy9M',
    appId: '1:124863240778:web:5eee0919f3b47d8e37a4b3',
    messagingSenderId: '124863240778',
    projectId: 'emergency-c1b8b',
    authDomain: 'emergency-c1b8b.firebaseapp.com',
    storageBucket: 'emergency-c1b8b.appspot.com',
  );

}